/**
 * Disposable / fake-email domain blocklist — kept aligned with trefolio
 * (`stocktracker/src/lib/schemas.ts` BLOCKED_EMAIL_DOMAINS).
 */

const BLOCKED_EMAIL_DOMAINS = new Set([
  // Guerrilla Mail family
  "guerrillamail.com",
  "guerrillamail.de",
  "guerrillamail.info",
  "guerrillamail.net",
  "guerrillamail.org",
  "guerrillamailblock.com",
  "grr.la",
  "sharklasers.com",

  // Mailinator family
  "mailinator.com",
  "mailinator.net",
  "mailinator2.com",

  // Temp / disposable mail services
  "tempmail.com",
  "temp-mail.org",
  "temp-mail.io",
  "tempail.com",
  "tempr.email",
  "tmpmail.org",
  "tmpmail.net",
  "tmail.ws",
  "10minutemail.com",
  "10minutemail.net",
  "minutemail.com",
  "throwaway.email",
  "throwaway.com",
  "yopmail.com",
  "yopmail.fr",
  "dispostable.com",
  "mailnesia.com",
  "maildrop.cc",
  "discard.email",
  "trashmail.com",
  "trashmail.me",
  "trashmail.net",
  "trashmail.org",
  "mohmal.com",
  "fakeinbox.com",
  "mailcatch.com",
  "nada.email",
  "getnada.com",
  "emailondeck.com",
  "spamgourmet.com",
  "mytemp.email",
  "burnermail.io",
  "inboxkitten.com",
  "harakirimail.com",
  "mailsac.com",
  "crazymailing.com",
  "moakt.com",
  "mail7.io",
  "emailfake.com",
  "generator.email",

  // User-reported spam / fake-email domains
  "email.com",
  "sharebot.net",
  "ymail.com",

  // Additional disposable providers
  "guerrillamail.biz",
  "tempinbox.com",
  "tempmailaddress.com",
  "tempmails.net",
  "disposableemailaddresses.emailmiser.com",
  "mailtemp.info",
  "mt2015.com",
  "thankyou2010.com",
  "trash-mail.com",
  "trashymail.com",
  "trashymail.net",
  "bugmenot.com",
  "binkmail.com",
  "safetymail.info",
  "filzmail.com",
  "mailexpire.com",
  "tempmailo.com",
  "tempomail.fr",
  "spambox.us",
  "spamfree24.org",
  "getairmail.com",
  "meltmail.com",
  "throwam.com",
  "mailnull.com",
  "jetable.org",
  "incognitomail.org",
  "anonymbox.com",
  "mintemail.com",
  "armyspy.com",
  "cuvox.de",
  "dayrep.com",
  "einrot.com",
  "fleckens.hu",
  "gustr.com",
  "jourrapide.com",
  "rhyta.com",
  "superrito.com",
  "teleworm.us",
  "courrieltemporaire.com",
  "nomail.xl.cx",
  "mailforspam.com",
  "safetypost.de",
  "despammed.com",
  "devnullmail.com",
  "spamcero.com",
  "spamcorptastic.com",
  "spamherelots.com",
  "spamhereplease.com",
  "spamthisplease.com",
]);

export function isBlockedEmailDomain(email: string): boolean {
  const domain = email.split("@")[1]?.toLowerCase();
  return !!domain && BLOCKED_EMAIL_DOMAINS.has(domain);
}
